name: CICD

on: 
  push:
    branches:
      - "**"
  pull_request:
    branches: ["master", "development"]
  create:

permissions:
  id-token: write
  contents: read

jobs:

  CI:
    uses: ./.github/workflows/pipeline-build.yml
    with:
      build-artifacts: true

  CD-development:
    if: github.ref == 'refs/heads/development'  
    uses: ./.github/workflows/pipeline-deploy-appservice.yml
    secrets: inherit
    needs: [ CI ]
    with:
      environmentName: Dev

  CD-QA:
    if: contains( github.ref, 'certification' )  
    uses: ./.github/workflows/pipeline-deploy-appservice.yml
    secrets: inherit
    needs: [ CI ]
    with:
      environmentName: QA

  CD-production:
    if: github.ref == 'refs/heads/master'  
    uses: ./.github/workflows/pipeline-deploy-appservice.yml
    secrets: inherit
    needs: [ CI ]
    with:
      environmentName: Prpd